FROM openjdk:8

ADD target/stock-0.0.1-SNAPSHOT.jar app.jar

RUN sh -c 'echo spring.datasource.url=jdbc:mysql://mysql:3306/stock_market?serverTimezone=UTC&useSSL=false > application.properties'
RUN sh -c 'echo spring.datasource.username=root    > application.properties'
RUN sh -c 'echo spring.datasource.password=c0nygre > application.properties'

ENTRYPOINT ["java","-jar","/app.jar"]
