spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 889566
    url: jdbc:mysql://localhost:3306/stock_market?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
server:
  port: 8090
